import Head from "next/head";
import Image from "next/image";
import FirstSection from "../components/HomePage/FirstSection";
import PriceSection from "../components/HomePage/PriceSection";
import SecondSection from "../components/HomePage/SecondSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Diving Djursland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        {/* First section */}
        <div className="bg-gradient pt-5 relative">
          <FirstSection />
          <div className="relative">
            <Image
              layout="responsive"
              height="5vh"
              objectFit="cover"
              width="100%"
              src="/images/wavessvg.svg"
              alt=""
            />
          </div>
        </div>

        {/* Second section */}
        <div className="s-section pt-10 flex flex-col gap-10">
          <SecondSection />
          <div>
            <Image
              layout="responsive"
              height="5vh"
              objectFit="cover"
              width="100%"
              src="/images/wavessvg-blue.svg"
              alt=""
            />
          </div>
        </div>

        {/* Price & Team section */}
        <div className="bg-gradient">
          <PriceSection />
        </div>
      </main>
    </div>
  );
}
